Task 4
js-tasks-ru/htmlcss-20230411_brynkina-tatyana pull request #5
Opened 2023-04-24 19:23 UTC by Olnovikov

task 4

2023-04-25 11:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-25 11:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-25 12:52 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
в модификаторах модифицируем только ширину (ширину задаем в процентах), остальное - либо в классе элемента либо через родителя (отступы между элементами)

2023-04-25 12:54 UTC, Olnovikov commented on 04-lection2/01-histogram/histogram.css
> +    margin-left: 1px;
так я и обнулил) там есть

2023-04-25 20:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-26 13:49 UTC, GSemikozov requested changes

2023-04-26 13:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 19px 24px 24px 26px;
`16px 24px 24px`

2023-04-26 13:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    text-align: right;
лишнее

2023-04-26 13:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
flex-basis: 9px

2023-04-26 13:49 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <div class="histogram__info__content">
тут не поменяли

2023-04-26 13:49 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__item-short {
.skeleton__item_short и тд ниже

2023-04-26 19:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-28 14:26 UTC, GSemikozov approved these changes

2023-04-28 14:27 UTC, merged